import {describe,it,expect} from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {openAgentOfficeDatabase} from './database.js';import {CapabilityMatcher,CapabilityRepository,normalizedModelCapabilities} from './capabilityCore.js';
function fx(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'cap-core-'));const db=openAgentOfficeDatabase({dataDir:d,databasePath:path.join(d,'db.sqlite'),logLevel:'silent'});const t=new Date().toISOString();return{d,db,t,agent(id:string,enabled=1){db.connection.prepare(`INSERT INTO agents(id,name,slug,enabled,created_at,updated_at)VALUES(?,?,?,?,?,?)`).run(id,id,id,enabled,t,t)},done(){db.connection.close();fs.rmSync(d,{recursive:true,force:true})}}}
describe('V3.1 Capability Core',()=>{
 it('seeds taxonomy idempotently and supports unknown extensible capabilities',()=>{const f=fx();try{const r=new CapabilityRepository(f.db.connection);r.seed();const n=r.list().length;r.seed();expect(r.list().length).toBe(n);expect(r.get('software.frontend.react')?.parent_key).toBe('software.frontend');r.create({key:'legal.contracts',label:'Contracts',domain:'legal'});expect(r.get('legal.contracts')?.domain).toBe('legal')}finally{f.done()}});
 it('keeps verified evidence server-owned and excludes disabled links/agents',()=>{const f=fx();try{const r=new CapabilityRepository(f.db.connection);r.seed();f.agent('a');f.agent('disabled',0);r.replaceAgent('a',[{capability_key:'software',declared_score:.9,enabled:false}]);expect(new CapabilityMatcher(f.db.connection).match([{key:'software'}]).find(x=>x.agent_id==='a')?.eligible).toBe(false);expect(new CapabilityMatcher(f.db.connection).match([{key:'software'}]).some(x=>x.agent_id==='disabled')).toBe(false);expect(r.listAgent('a')[0].verified_score).toBeNull()}finally{f.done()}});
 it('matches exact and child specialist deterministically, preserving mandatory blockers',()=>{const f=fx();try{const r=new CapabilityRepository(f.db.connection);r.seed();f.agent('react');f.agent('generic');r.replaceAgent('react',[{capability_key:'software.frontend.react',declared_score:1}]);r.replaceAgent('generic',[{capability_key:'software',declared_score:1}]);const parent=new CapabilityMatcher(f.db.connection).match([{key:'software',minimum:.2}]);expect(parent.find(x=>x.agent_id==='react')?.eligible).toBe(true);expect(parent.find(x=>x.agent_id==='react')?.matched[0]?.actual).toBe('software.frontend.react');const child=new CapabilityMatcher(f.db.connection).match([{key:'software.frontend.react',mandatory:true}]);expect(child.find(x=>x.agent_id==='generic')?.blockers).toContain('missing:software.frontend.react')}finally{f.done()}});
 it('treats required tools as hard blockers',()=>{const f=fx();try{const r=new CapabilityRepository(f.db.connection);r.seed();f.agent('a');r.replaceAgent('a',[{capability_key:'software',declared_score:1}]);f.db.connection.prepare(`INSERT INTO agent_tool_policies(agent_id,enabled,allowed_tools_json,approval_mode,max_tool_steps,updated_at)VALUES('a',1,'["read_file"]','safe',12,?)`).run(f.t);const m=new CapabilityMatcher(f.db.connection);expect(m.match([{key:'software'}],['read_file'])[0].eligible).toBe(true);expect(m.match([{key:'software'}],['write_file'])[0].blockers).toContain('tool:write_file')}finally{f.done()}});
 it('handles a 500-agent fixture without prompt scanning and never promotes missing mandatory capability',()=>{const f=fx();try{const r=new CapabilityRepository(f.db.connection);r.seed();const ins=f.db.connection.prepare(`INSERT INTO agents(id,name,slug,enabled,created_at,updated_at)VALUES(?,?,?,?,?,?)`);const cap=f.db.connection.prepare(`INSERT INTO agent_capabilities(agent_id,capability_key,declared_score,confidence,evidence_count,source,enabled,updated_at)VALUES(?,?,1,1,0,'manual',1,?)`);f.db.connection.transaction(()=>{for(let i=0;i<500;i++){const id=`agent-${i}`;ins.run(id,id,id,1,f.t,f.t);cap.run(id,i%2===0?'software.frontend.react':'marketing',f.t)}})();const out=new CapabilityMatcher(f.db.connection).match([{key:'software.frontend.react',mandatory:true,minimum:.5}]);const fixture=out.filter(x=>x.agent_id.startsWith('agent-'));expect(fixture).toHaveLength(500);expect(fixture.filter(x=>x.eligible)).toHaveLength(250);expect(fixture.filter(x=>x.missing.includes('software.frontend.react')).every(x=>!x.eligible)).toBe(true)}finally{f.done()}});
 it('normalizes existing provider model metadata without duplicating storage',()=>{expect(normalizedModelCapabilities({vision:true,context_window:128000,label:'x',nested:{}})).toEqual({vision:true,context_window:128000})});
 it('preserves learned verification evidence when declared capabilities are edited manually',()=>{const f=fx();try{const r=new CapabilityRepository(f.db.connection);r.seed();f.agent('learned');r.replaceAgent('learned',[{capability_key:'software.backend',declared_score:.5,source:'learned'}]);f.db.connection.prepare("UPDATE agent_capabilities SET verified_score=.9,confidence=.8,evidence_count=7,source='learned' WHERE agent_id='learned' AND capability_key='software.backend'").run();r.replaceAgent('learned',[{capability_key:'software.backend',declared_score:.75,source:'manual'}]);const cap=r.listAgent('learned')[0];expect(cap.declared_score).toBe(.75);expect(cap.verified_score).toBe(.9);expect(cap.confidence).toBe(.8);expect(cap.evidence_count).toBe(7);expect(cap.source).toBe('learned')}finally{f.done()}});

});
