import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {openAgentOfficeDatabase} from './database.js';
import {ExecutionGraphService} from './executionGraph.js';
import {DurableExecutionService} from './durableExecution.js';

function fx(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'durable-'));const db=openAgentOfficeDatabase({dataDir:d,databasePath:path.join(d,'db.sqlite'),logLevel:'silent'}),t=new Date().toISOString();db.connection.prepare(`INSERT INTO projects(id,name,root_path,created_at,updated_at)VALUES('p','P',?,?,?)`).run(d,t,t);return{d,db,t,done(){db.connection.close();fs.rmSync(d,{recursive:true,force:true})}}}
function runningAttempt(db:any,step:any,resume:string){db.prepare(`UPDATE execution_plans SET status='running' WHERE id=?`).run(step.plan_id);db.prepare(`UPDATE execution_steps SET status='running',resume_state=? WHERE id=?`).run(resume,step.id);db.prepare(`INSERT INTO step_attempts(id,step_id,attempt_number,status,started_at)VALUES(?,?,1,'running',?)`).run('attempt-'+step.id,step.id,new Date().toISOString())}

describe('V3.5 durable runs and replanning',()=>{
 it('creates durable checkpoints without persisting tool inputs or secrets',()=>{const f=fx();try{const p=new ExecutionGraphService(f.db.connection).createValidated({project_id:'p',goal:'x',steps:[{key:'a',goal:'a'}]})!;const rows=f.db.connection.prepare('SELECT reason,snapshot_json FROM execution_checkpoints WHERE plan_id=?').all(p.id) as any[];expect(rows.length).toBeGreaterThan(0);expect(rows[0].reason).toBe('plan_validated');expect(rows[0].snapshot_json).not.toContain('sk-');expect((f.db.connection.prepare(`SELECT COUNT(*) n FROM activity_events WHERE type='checkpoint.created'`).get() as any).n).toBeGreaterThan(0)}finally{f.done()}});
 it('requeues interrupted safe work and expires stale runtime locks',()=>{const f=fx();try{const g=new ExecutionGraphService(f.db.connection),p=g.createValidated({project_id:'p',goal:'x',steps:[{key:'a',goal:'a'}]})!,s=p.steps[0];runningAttempt(f.db.connection,s,'running_model');f.db.connection.prepare(`INSERT INTO resource_locks(id,project_id,resource_key,mode,owner_step_id,status,acquired_at,heartbeat_at,expires_at)VALUES('l','p','file:x','read',?,'active',?,?,?)`).run(s.id,f.t,f.t,new Date(Date.now()+60000).toISOString());const r=new DurableExecutionService(f.db.connection).recoverAll();expect(r).toMatchObject({recovered_plans:1,retryable_steps:1,manual_review_steps:0});expect(g.getPlan(p.id)?.steps[0]).toMatchObject({status:'queued',resume_state:'queued'});expect(f.db.connection.prepare(`SELECT status FROM resource_locks WHERE id='l'`).get()).toEqual({status:'expired'});expect(f.db.connection.prepare(`SELECT status,error_json FROM step_attempts WHERE id=?`).get('attempt-'+s.id)).toMatchObject({status:'failed'})}finally{f.done()}});
 it('blocks uncertain side effects for manual review instead of silently retrying',()=>{const f=fx();try{const g=new ExecutionGraphService(f.db.connection),p=g.createValidated({project_id:'p',goal:'x',steps:[{key:'a',goal:'a',required_tools:['write_file'],resource_locks:[{resource_key:'file:x',mode:'write'}]}]})!,s=p.steps[0];runningAttempt(f.db.connection,s,'running_tool_side_effect');const r=new DurableExecutionService(f.db.connection).recoverAll();expect(r.manual_review_steps).toBe(1);expect(g.getPlan(p.id)?.steps[0]).toMatchObject({status:'blocked',resume_state:'blocked_manual_review'});expect((f.db.connection.prepare(`SELECT COUNT(*) n FROM activity_events WHERE type='run.blocked_manual_review'`).get() as any).n).toBe(1);new DurableExecutionService(f.db.connection).manualReviewResolve(s.id,'retry');expect(g.getPlan(p.id)?.steps[0]).toMatchObject({status:'queued',resume_state:'queued'})}finally{f.done()}});
 it('preserves non-expired V3 approvals across recovery',()=>{const f=fx();try{const g=new ExecutionGraphService(f.db.connection),p=g.createValidated({project_id:'p',goal:'x',steps:[{key:'a',goal:'a'}]})!,s=p.steps[0];f.db.connection.prepare(`UPDATE execution_plans SET status='running' WHERE id=?`).run(p.id);f.db.connection.prepare(`INSERT INTO tool_approvals(id,project_id,run_id,agent_id,tool_name,input_json,reason,status,created_at,execution_plan_id,execution_step_id,expires_at,tool_invocation_id)VALUES('approval','p',NULL,NULL,'write_file','{"path":"x"}','test','pending',?,?,?,?,?)`).run(f.t,p.id,s.id,new Date(Date.now()+60000).toISOString(),'call-1');new DurableExecutionService(f.db.connection).recoverAll();expect(f.db.connection.prepare(`SELECT status,execution_plan_id,tool_invocation_id FROM tool_approvals WHERE id='approval'`).get()).toEqual({status:'pending',execution_plan_id:p.id,tool_invocation_id:'call-1'})}finally{f.done()}});
 it('commits a versioned replan, preserves compatible completed work and never erases v1',()=>{const f=fx();try{const g=new ExecutionGraphService(f.db.connection),p=g.createValidated({project_id:'p',goal:'ship',budget:{max_replans:2},steps:[{key:'a',goal:'same'},{key:'b',goal:'old'}]})!,a=p.steps.find((x:any)=>x.key==='a');f.db.connection.prepare(`UPDATE execution_steps SET status='completed',resume_state='completed' WHERE id=?`).run(a.id);f.db.connection.prepare(`INSERT INTO execution_artifacts(id,plan_id,step_id,type,uri,payload_json,created_at)VALUES('artifact',?,?, 'file','a.txt','{}',?)`).run(p.id,a.id,f.t);const svc=new DurableExecutionService(f.db.connection),req=svc.requestReplan(p.id,'new constraint','user_orientation');const next=svc.commitReplan(req.request_id,{project_id:'p',goal:'ship',budget:{max_replans:2},steps:[{key:'a',goal:'same'},{key:'b',goal:'new'}]})!;expect(f.db.connection.prepare('SELECT status FROM execution_plans WHERE id=?').get(p.id)).toEqual({status:'superseded'});expect(next).toMatchObject({version:2,parent_plan_id:p.id,replan_count:1});expect(next.steps.find((x:any)=>x.key==='a').status).toBe('completed');expect((f.db.connection.prepare('SELECT COUNT(*) n FROM execution_artifacts WHERE plan_id=?').get(next.id) as any).n).toBe(1);expect((f.db.connection.prepare(`SELECT COUNT(*) n FROM execution_checkpoints WHERE plan_id=? AND reason='replan_committed'`).get(next.id) as any).n).toBe(1)}finally{f.done()}});
 it('enforces max replan budget across plan versions',()=>{const f=fx();try{const g=new ExecutionGraphService(f.db.connection),p=g.createValidated({project_id:'p',goal:'x',budget:{max_replans:1},steps:[{key:'a',goal:'a'}]})!,svc=new DurableExecutionService(f.db.connection),req=svc.requestReplan(p.id,'reason','provider_unavailable'),next=svc.commitReplan(req.request_id,{project_id:'p',goal:'x',budget:{max_replans:1},steps:[{key:'a',goal:'changed'}]})!;expect(()=>svc.requestReplan(next.id,'another','runtime_gap')).toThrow('REPLAN_LIMIT_EXCEEDED')}finally{f.done()}});
 it('persists user interruption commands independently of process memory',()=>{const f=fx();try{const p=new ExecutionGraphService(f.db.connection).createValidated({project_id:'p',goal:'x',steps:[{key:'a',goal:'a'}]})!,svc=new DurableExecutionService(f.db.connection);const cmd=svc.enqueueCommand(p.id,'orient',{message:'priorize testes'});expect(f.db.connection.prepare('SELECT command_type,status,payload_json FROM execution_commands WHERE id=?').get(cmd.command_id)).toMatchObject({command_type:'orient',status:'pending'});f.db.connection.close();const db2=openAgentOfficeDatabase({dataDir:f.d,databasePath:path.join(f.d,'db.sqlite'),logLevel:'silent'});expect(db2.connection.prepare('SELECT status FROM execution_commands WHERE id=?').get(cmd.command_id)).toEqual({status:'pending'});db2.connection.close();fs.rmSync(f.d,{recursive:true,force:true})}catch(e){try{f.db.connection.close()}catch{};throw e}});
});
