import crypto from 'node:crypto';import type{Database}from'better-sqlite3';import type{CapabilityRequirement}from'./capabilityCore.js';
export interface ExecutionBudget{max_agents?:number;max_parallel?:number;max_cost?:number;max_tokens?:number;max_wall_time?:number;max_step_retries?:number;max_tool_calls?:number}
export interface StepDraft{key:string;title?:string;goal:string;required_capabilities?:CapabilityRequirement[];required_tools?:string[];assigned_agent_id?:string|null;assigned_team_id?:string|null;risk?:'low'|'medium'|'high';expected_outputs?:string[];success_criteria?:string[];timeout_ms?:number;retry_policy?:{max_retries?:number};priority?:number}
export interface DependencyDraft{step_key:string;depends_on_key:string;dependency_type?:'hard'|'artifact'|'approval'}
export interface PlanDraft{orchestration_run_id?:string|null;project_id:string;goal:string;rationale?:string;budget?:ExecutionBudget;steps:StepDraft[];dependencies?:DependencyDraft[]}
export interface WorkPacket{objective:string;completed_work:string[];changed_files:string[];decisions:string[];tests:string[];artifacts:string[];open_issues:string[];next_action:string;constraints:string[]}
export interface StepExecutor{execute(input:{plan_id:string;step_id:string;step_key:string;agent_id:string|null;goal:string;timeout_ms:number}):Promise<{summary:string;artifacts?:Array<{type:string;uri?:string;payload?:Record<string,unknown>}>;work_packet?:WorkPacket}>}
const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),json=(v:unknown)=>JSON.stringify(v??{}),arr=(v:unknown)=>JSON.stringify(v??[]);
export class ExecutionGraphService{
 constructor(private db:Database){}
 createValidated(d:PlanDraft){this.validateDraft(d);const planId=uid(),t=now(),budget=this.normalizeBudget(d.budget??{});const ids=new Map<string,string>();this.db.transaction(()=>{this.db.prepare(`INSERT INTO execution_plans(id,orchestration_run_id,project_id,version,status,goal,rationale,budget_json,created_at,updated_at)VALUES(?,?,?,1,'validated',?,?,?,?,?)`).run(planId,d.orchestration_run_id??null,d.project_id,d.goal.trim(),d.rationale??'',json(budget),t,t);const ins=this.db.prepare(`INSERT INTO execution_steps(id,plan_id,key,title,goal,required_capabilities_json,required_tools_json,assigned_agent_id,assigned_team_id,status,risk,expected_outputs_json,success_criteria_json,timeout_ms,retry_policy_json,priority,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,'queued',?,?,?,?,?,?,?,?)`);for(const s of d.steps){const sid=uid();ids.set(s.key,sid);ins.run(sid,planId,s.key,s.title??s.key,s.goal.trim(),arr(s.required_capabilities??[]),arr(s.required_tools??[]),s.assigned_agent_id??null,s.assigned_team_id??null,s.risk??'low',arr(s.expected_outputs??[]),arr(s.success_criteria??[]),Math.max(1000,s.timeout_ms??60000),json({max_retries:Math.max(0,s.retry_policy?.max_retries??budget.max_step_retries??0)}),s.priority??0,t,t)}const dep=this.db.prepare('INSERT INTO step_dependencies(step_id,depends_on_step_id,dependency_type)VALUES(?,?,?)');for(const x of d.dependencies??[])dep.run(ids.get(x.step_key),ids.get(x.depends_on_key),x.dependency_type??'hard')})();return this.getPlan(planId)}
 validateDraft(d:PlanDraft){if(!d.project_id||!this.db.prepare('SELECT 1 FROM projects WHERE id=?').get(d.project_id))throw new Error('EXECUTION_PROJECT_NOT_FOUND');if(!d.goal?.trim())throw new Error('EXECUTION_PLAN_GOAL_REQUIRED');if(!Array.isArray(d.steps)||!d.steps.length)throw new Error('EXECUTION_STEPS_REQUIRED');const keys=new Set<string>();for(const s of d.steps){if(!s.key?.trim()||keys.has(s.key))throw new Error('EXECUTION_STEP_KEY_INVALID');keys.add(s.key);if(!s.goal?.trim())throw new Error('EXECUTION_STEP_GOAL_REQUIRED');if(s.assigned_agent_id&&!this.db.prepare(`SELECT 1 FROM agents a JOIN providers p ON p.id=a.provider_id AND p.enabled=1 JOIN provider_models m ON m.id=a.model_id AND m.enabled=1 WHERE a.id=? AND a.enabled=1`).get(s.assigned_agent_id))throw new Error('EXECUTION_ASSIGNMENT_INVALID')}for(const x of d.dependencies??[])if(!keys.has(x.step_key)||!keys.has(x.depends_on_key)||x.step_key===x.depends_on_key)throw new Error('EXECUTION_DEPENDENCY_INVALID');this.assertAcyclic([...keys],d.dependencies??[]);this.normalizeBudget(d.budget??{});return true}
 private assertAcyclic(keys:string[],deps:DependencyDraft[]){const indeg=new Map(keys.map(k=>[k,0])),next=new Map(keys.map(k=>[k,[] as string[]]));for(const d of deps){indeg.set(d.step_key,(indeg.get(d.step_key)??0)+1);next.get(d.depends_on_key)!.push(d.step_key)}const q=keys.filter(k=>indeg.get(k)===0),out:string[]=[];while(q.length){const k=q.shift()!;out.push(k);for(const n of next.get(k)??[]){indeg.set(n,indeg.get(n)!-1);if(indeg.get(n)===0)q.push(n)}}if(out.length!==keys.length)throw new Error('EXECUTION_DAG_CYCLE')}
 private normalizeBudget(b:ExecutionBudget){const n=(v:number|undefined,d:number,min=1)=>Number.isFinite(v)?Math.max(min,Number(v)):d;return{max_agents:n(b.max_agents,8),max_parallel:n(b.max_parallel,3),max_cost:n(b.max_cost,100,0),max_tokens:n(b.max_tokens,500000),max_wall_time:n(b.max_wall_time,3600000),max_step_retries:n(b.max_step_retries,2,0),max_tool_calls:n(b.max_tool_calls,100,0)}}
 getPlan(id:string){const plan=this.db.prepare('SELECT * FROM execution_plans WHERE id=?').get(id) as any;if(!plan)return null;const steps=this.db.prepare('SELECT * FROM execution_steps WHERE plan_id=? ORDER BY priority DESC,created_at,key').all(id) as any[],deps=this.db.prepare(`SELECT d.*,s.key step_key,p.key depends_on_key FROM step_dependencies d JOIN execution_steps s ON s.id=d.step_id JOIN execution_steps p ON p.id=d.depends_on_step_id WHERE s.plan_id=?`).all(id);return{...plan,budget:JSON.parse(plan.budget_json),steps:steps.map(s=>({...s,required_capabilities:JSON.parse(s.required_capabilities_json),required_tools:JSON.parse(s.required_tools_json),retry_policy:JSON.parse(s.retry_policy_json)})),dependencies:deps}}
 readySteps(planId:string){const plan=this.db.prepare('SELECT budget_json,status FROM execution_plans WHERE id=?').get(planId) as any;if(!plan)return[];const budget=JSON.parse(plan.budget_json),running=(this.db.prepare(`SELECT COUNT(*) n FROM execution_steps WHERE plan_id=? AND status='running'`).get(planId)as any).n,slots=Math.max(0,budget.max_parallel-running);if(!slots)return[];return this.db.prepare(`SELECT s.* FROM execution_steps s WHERE s.plan_id=? AND s.status IN ('queued','ready') AND NOT EXISTS(SELECT 1 FROM step_dependencies d JOIN execution_steps p ON p.id=d.depends_on_step_id WHERE d.step_id=s.id AND p.status<>'completed') ORDER BY s.priority DESC,s.created_at,s.key LIMIT ?`).all(planId,slots) as any[]}
}
export class ResourceLockManager{
 constructor(private db:Database){}
 acquire(input:{project_id:string;resource_key:string;mode:'read'|'write'|'exclusive';step_id:string;attempt_id?:string|null;ttl_ms?:number}){this.reconcile(input.project_id);const conflicts=this.db.prepare(`SELECT mode FROM resource_locks WHERE project_id=? AND resource_key=? AND status='active'`).all(input.project_id,input.resource_key) as any[];if(conflicts.some(x=>input.mode!=='read'||x.mode!=='read'))return null;const id=uid(),t=now(),exp=new Date(Date.now()+Math.max(1000,input.ttl_ms??60000)).toISOString();this.db.prepare(`INSERT INTO resource_locks(id,project_id,resource_key,mode,owner_step_id,owner_attempt_id,status,acquired_at,heartbeat_at,expires_at)VALUES(?,?,?,?,?,?,'active',?,?,?)`).run(id,input.project_id,input.resource_key,input.mode,input.step_id,input.attempt_id??null,t,t,exp);return id}
 heartbeat(id:string,ttl=60000){const t=now(),exp=new Date(Date.now()+Math.max(1000,ttl)).toISOString();return this.db.prepare(`UPDATE resource_locks SET heartbeat_at=?,expires_at=? WHERE id=? AND status='active'`).run(t,exp,id).changes===1}
 release(id:string){return this.db.prepare(`UPDATE resource_locks SET status='released' WHERE id=? AND status='active'`).run(id).changes===1}
 reconcile(projectId?:string){const q=projectId?`UPDATE resource_locks SET status='expired' WHERE project_id=? AND status='active' AND expires_at<=?`:`UPDATE resource_locks SET status='expired' WHERE status='active' AND expires_at<=?`;return projectId?this.db.prepare(q).run(projectId,now()).changes:this.db.prepare(q).run(now()).changes}
}
export class ExecutionScheduler{
 constructor(private db:Database,private executor:StepExecutor,private graph=new ExecutionGraphService(db)){}
 async tick(planId:string){const plan=this.graph.getPlan(planId);if(!plan)throw new Error('EXECUTION_PLAN_NOT_FOUND');const budget=plan.budget as Required<ExecutionBudget>;const started=new Date(plan.created_at).getTime();if(Date.now()-started>budget.max_wall_time){this.db.prepare(`UPDATE execution_plans SET status='failed',updated_at=? WHERE id=?`).run(now(),planId);this.db.prepare(`UPDATE execution_steps SET status='blocked',updated_at=? WHERE plan_id=? AND status IN ('queued','ready')`).run(now(),planId);return{started:0,blocked:'budget_exceeded'}}const ready=this.graph.readySteps(planId);if(!ready.length){this.finishPlan(planId);return{started:0}}this.db.prepare(`UPDATE execution_plans SET status='running',updated_at=? WHERE id=? AND status='validated'`).run(now(),planId);await Promise.all(ready.map(s=>this.runStep(planId,s,budget)));this.finishPlan(planId);return{started:ready.length}}
 private async runStep(planId:string,s:any,budget:Required<ExecutionBudget>){const prior=(this.db.prepare('SELECT COUNT(*) n FROM step_attempts WHERE step_id=?').get(s.id)as any).n;if(prior>budget.max_step_retries){this.db.prepare(`UPDATE execution_steps SET status='failed',updated_at=? WHERE id=?`).run(now(),s.id);return}const attempt=uid(),n=prior+1,t=now();this.db.transaction(()=>{this.db.prepare(`UPDATE execution_steps SET status='running',updated_at=? WHERE id=? AND status IN ('queued','ready')`).run(t,s.id);this.db.prepare(`INSERT INTO step_attempts(id,step_id,attempt_number,status,started_at)VALUES(?,?,?,'running',?)`).run(attempt,s.id,n,t)})();try{const result=await Promise.race([this.executor.execute({plan_id:planId,step_id:s.id,step_key:s.key,agent_id:s.assigned_agent_id,goal:s.goal,timeout_ms:s.timeout_ms}),new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('EXECUTION_STEP_TIMEOUT')),s.timeout_ms))]);const end=now();this.db.transaction(()=>{this.db.prepare(`UPDATE step_attempts SET status='completed',ended_at=?,result_summary=? WHERE id=?`).run(end,result.summary,attempt);this.db.prepare(`UPDATE execution_steps SET status='completed',updated_at=? WHERE id=?`).run(end,s.id);for(const a of result.artifacts??[])this.db.prepare(`INSERT INTO execution_artifacts(id,plan_id,step_id,type,uri,payload_json,created_at)VALUES(?,?,?,?,?,?,?)`).run(uid(),planId,s.id,a.type,a.uri??null,json(a.payload??{}),end);if(result.work_packet)this.db.prepare(`INSERT INTO execution_artifacts(id,plan_id,step_id,type,payload_json,created_at)VALUES(?,?,?,'work_packet',?,?)`).run(uid(),planId,s.id,json(validateWorkPacket(result.work_packet)),end)})}catch(e){const end=now(),timeout=e instanceof Error&&e.message==='EXECUTION_STEP_TIMEOUT';this.db.prepare(`UPDATE step_attempts SET status=?,ended_at=?,error_json=? WHERE id=?`).run(timeout?'timed_out':'failed',end,json({code:timeout?'EXECUTION_STEP_TIMEOUT':'EXECUTION_STEP_FAILED'}),attempt);const canRetry=n<=Math.min(budget.max_step_retries,JSON.parse(s.retry_policy_json||'{}').max_retries??budget.max_step_retries);this.db.prepare(`UPDATE execution_steps SET status=?,updated_at=? WHERE id=?`).run(canRetry?'queued':'failed',end,s.id)}}
 private finishPlan(planId:string){const rows=this.db.prepare('SELECT status FROM execution_steps WHERE plan_id=?').all(planId)as any[];if(rows.some(x=>x.status==='failed'))this.db.prepare(`UPDATE execution_plans SET status='failed',updated_at=? WHERE id=?`).run(now(),planId);else if(rows.length&&rows.every(x=>x.status==='completed'))this.db.prepare(`UPDATE execution_plans SET status='completed',updated_at=? WHERE id=?`).run(now(),planId)}
}
export function validateWorkPacket(x:WorkPacket):WorkPacket{if(!x||typeof x.objective!=='string'||typeof x.next_action!=='string')throw new Error('WORK_PACKET_INVALID');for(const k of['completed_work','changed_files','decisions','tests','artifacts','open_issues','constraints']as const)if(!Array.isArray(x[k])||!x[k].every(v=>typeof v==='string'))throw new Error('WORK_PACKET_INVALID');return x}
