import{describe,it,expect}from'vitest';import fs from'node:fs';import os from'node:os';import path from'node:path';import{openAgentOfficeDatabase}from'./database.js';import{CapabilityRepository}from'./capabilityCore.js';import{GapAnalysisService}from'./gapAnalysis.js';
function fx(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'gap-'));const db=openAgentOfficeDatabase({dataDir:d,databasePath:path.join(d,'db.sqlite'),logLevel:'silent'}),t=new Date().toISOString();db.connection.prepare(`INSERT INTO providers(id,name,protocol_driver,enabled,created_at,updated_at)VALUES('p','p','openai_chat',1,?,?)`).run(t,t);db.connection.prepare(`INSERT INTO provider_models(id,provider_id,model_id,display_name,enabled,created_at,updated_at)VALUES('m','p','m','m',1,?,?,?)`).run(t,t);const r=new CapabilityRepository(db.connection);r.seed();const agent=(id:string,enabled=1,caps:string[]=[],tools:string[]=[])=>{db.connection.prepare(`INSERT INTO agents(id,name,slug,provider_id,model_id,enabled,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?)`).run(id,id,id,'p','m',enabled,t,t);r.replaceAgent(id,caps.map(capability_key=>({capability_key,declared_score:1})));if(tools.length)db.connection.prepare(`INSERT INTO agent_tool_policies(agent_id,enabled,allowed_tools_json,approval_mode,max_tool_steps,updated_at)VALUES(?,1,?,'safe',12,?)`).run(id,JSON.stringify(tools),t)};return{db,r,agent,done(){db.connection.close();fs.rmSync(d,{recursive:true,force:true})}}}
describe('V3.3 Gap Analysis',()=>{
 it('prefers one active agent that covers all requirements',()=>{const f=fx();try{f.agent('generalist',1,['software.frontend','software.backend']);f.agent('front',1,['software.frontend']);f.agent('back',1,['software.backend']);const x=new GapAnalysisService(f.db.connection).analyze([{key:'software.frontend'},{key:'software.backend'}]);expect(x.resolution).toBe('active_agent');expect(x.selected_agent_ids).toEqual(['generalist'])}finally{f.done()}});
 it('returns a minimal two-agent set and prunes redundant candidates',()=>{const f=fx();try{f.agent('front',1,['software.frontend']);f.agent('back',1,['software.backend']);f.agent('redundant',1,['software.frontend']);const x=new GapAnalysisService(f.db.connection).analyze([{key:'software.frontend'},{key:'software.backend'}]);expect(x.resolution).toBe('dynamic_team');expect(x.selected_agent_ids).toHaveLength(2);expect(x.selected_agent_ids).toContain('back')}finally{f.done()}});
 it('never auto-selects an inactive specialist',()=>{const f=fx();try{f.agent('specialist',0,['security']);const x=new GapAnalysisService(f.db.connection).analyze([{key:'security'}]);expect(x.resolution).toBe('inactive_agent_available');expect(x.selected_agent_ids).toEqual([]);expect(x.inactive_agent_ids).toEqual(['specialist'])}finally{f.done()}});
 it('does not select an agent whose provider/model is unavailable',()=>{const f=fx();try{f.agent('a',1,['research']);f.db.connection.prepare(`UPDATE provider_models SET enabled=0 WHERE id='m'`).run();const x=new GapAnalysisService(f.db.connection).analyze([{key:'research'}]);expect(x.selected_agent_ids).toEqual([]);expect(x.resolution).toBe('missing_capability')}finally{f.done()}});
 it('distinguishes a tool gap from a capability gap',()=>{const f=fx();try{f.agent('builder',1,['software'],['read_file']);const x=new GapAnalysisService(f.db.connection).analyze([{key:'software'}],['write_file']);expect(x.resolution).toBe('missing_tool');expect(x.gaps.some(g=>g.missing_tool==='write_file')).toBe(true);expect(x.gaps.every(g=>g.reason.includes('tool')||g.key==='tool')).toBe(true)}finally{f.done()}});
 it('reports a genuine capability gap with no candidates',()=>{const f=fx();try{const x=new GapAnalysisService(f.db.connection).analyze([{key:'video.editing'}]);expect(x.resolution).toBe('missing_capability');expect(x.gaps[0]).toMatchObject({key:'video.editing',blocking:true,discovered_at:'preflight'})}finally{f.done()}});
 it('property: selected sets are minimal after pruning',()=>{const f=fx();try{for(let i=0;i<60;i++)f.agent('f'+i,1,i%3===0?['software.frontend','software.backend']:i%2===0?['software.frontend']:['software.backend']);const x=new GapAnalysisService(f.db.connection).analyze([{key:'software.frontend'},{key:'software.backend'}]);expect(x.selected_agent_ids).toHaveLength(1)}finally{f.done()}});
});
