import type {Database} from 'better-sqlite3';import {CapabilityRepository,type CapabilityRequirement,type AgentCapability}from'./capabilityCore.js';import {TeamService}from'./teamService.js';import {AgentOperationsService}from'./agentOperations.js';
export type GapResolution='active_agent'|'inactive_agent_available'|'dynamic_team'|'existing_team'|'missing_tool'|'missing_integration'|'missing_capability';
export interface CapabilityGap{key:string;domain:string;required_level:number;reason:string;blocking:boolean;frequency_hint:number;candidate_alternatives:string[];missing_tool?:string;missing_integration?:string;confidence:number;discovered_at:'preflight'|'runtime'}
export interface GapAnalysisResult{resolution:GapResolution;selected_agent_ids:string[];selected_team_id?:string;inactive_agent_ids:string[];uncovered_requirements:string[];gaps:CapabilityGap[];explanation:string}
type Candidate={id:string;enabled:boolean;healthy:boolean;caps:AgentCapability[];tools:Set<string>};
const score=(c:AgentCapability)=> (c.verified_score??c.declared_score)*Math.max(.25,c.confidence);
export class GapAnalysisService{
 private caps:CapabilityRepository;constructor(private db:Database){this.caps=new CapabilityRepository(db)}
 analyze(requirements:CapabilityRequirement[],requiredTools:string[]=[]):GapAnalysisResult{this.caps.seed();const defs=new Map(this.caps.list().map(d=>[d.key,d]));for(const r of requirements)if(!defs.has(r.key))throw new Error('CAPABILITY_NOT_FOUND');const candidates=this.candidates();const mandatory=requirements.filter(r=>r.mandatory!==false);
  const covers=(c:Candidate,r:CapabilityRequirement)=>{const min=r.minimum??0;for(const cap of c.caps){if(!cap.enabled)continue;if(cap.capability_key===r.key&&score(cap)>=min)return true;if(r.allow_hierarchy!==false){let d=defs.get(cap.capability_key),seen=new Set<string>();while(d?.parent_key&&!seen.has(d.parent_key)){if(d.parent_key===r.key&&score(cap)>=min)return true;seen.add(d.parent_key);d=defs.get(d.parent_key)}}}return false};
  const toolOk=(c:Candidate)=>requiredTools.every(t=>c.tools.has(t));const active=candidates.filter(c=>c.enabled&&c.healthy),inactive=candidates.filter(c=>!c.enabled&&c.healthy);
  const single=active.filter(c=>mandatory.every(r=>covers(c,r))&&toolOk(c)).sort((a,b)=>this.quality(b)-this.quality(a)||a.id.localeCompare(b.id))[0];if(single)return{resolution:'active_agent',selected_agent_ids:[single.id],inactive_agent_ids:[],uncovered_requirements:[],gaps:[],explanation:'One active eligible agent covers all mandatory requirements.'};
  const selected=this.minimumSet(active,mandatory,covers,toolOk);const existing=this.findExistingTeam(mandatory,requiredTools);if(existing&&(!selected.length||existing.member_count<=selected.length))return{resolution:'existing_team',selected_agent_ids:[],selected_team_id:existing.id,inactive_agent_ids:[],uncovered_requirements:[],gaps:[],explanation:'An enabled permanent team covers the request without using more resources than the minimum dynamic set.'};if(selected.length&&mandatory.every(r=>selected.some(c=>covers(c,r))))return{resolution:'dynamic_team',selected_agent_ids:selected.map(c=>c.id),inactive_agent_ids:[],uncovered_requirements:[],gaps:[],explanation:'Minimum active-agent set covers all mandatory requirements.'};if(existing)return{resolution:'existing_team',selected_agent_ids:[],selected_team_id:existing.id,inactive_agent_ids:[],uncovered_requirements:[],gaps:[],explanation:'An enabled permanent team covers all mandatory requirements.'};
  const inactiveSingle=inactive.filter(c=>mandatory.every(r=>covers(c,r))&&toolOk(c)).sort((a,b)=>this.quality(b)-this.quality(a)||a.id.localeCompare(b.id))[0];if(inactiveSingle)return{resolution:'inactive_agent_available',selected_agent_ids:[],inactive_agent_ids:[inactiveSingle.id],uncovered_requirements:[],gaps:[],explanation:'An inactive eligible specialist can cover all requirements; activation requires user action.'};
  const uncovered=mandatory.filter(r=>!active.some(c=>covers(c,r)));const inactiveIds=[...new Set(uncovered.flatMap(r=>inactive.filter(c=>covers(c,r)&&toolOk(c)).map(c=>c.id)))];if(uncovered.length&&uncovered.every(r=>inactive.some(c=>covers(c,r)&&toolOk(c))))return{resolution:'inactive_agent_available',selected_agent_ids:[],inactive_agent_ids:inactiveIds,uncovered_requirements:uncovered.map(r=>r.key),gaps:[],explanation:'Inactive specialists cover the missing requirements; none are auto-selected.'};
  const gaps:CapabilityGap[]=[];for(const r of uncovered){const def=defs.get(r.key)!;const capable=candidates.filter(c=>covers(c,r));if(capable.length){const missing=requiredTools.filter(t=>!capable.some(c=>c.tools.has(t)));if(missing.length){for(const tool of missing)gaps.push({key:r.key,domain:def.domain,required_level:r.minimum??0,reason:'Capability exists but a required tool is unavailable to capable agents.',blocking:r.mandatory!==false,frequency_hint:0,candidate_alternatives:capable.map(c=>c.id),missing_tool:tool,confidence:.95,discovered_at:'preflight'});continue}}
   gaps.push({key:r.key,domain:def.domain,required_level:r.minimum??0,reason:'No eligible existing agent covers this capability.',blocking:r.mandatory!==false,frequency_hint:0,candidate_alternatives:capable.map(c=>c.id),confidence:.9,discovered_at:'preflight'})}
  if(!gaps.length&&requiredTools.length){const missing=requiredTools.filter(t=>!active.some(c=>c.tools.has(t)));for(const tool of missing)gaps.push({key:'tool',domain:'tooling',required_level:1,reason:'Required tool is not available to an active capable execution set.',blocking:true,frequency_hint:0,candidate_alternatives:[],missing_tool:tool,confidence:.95,discovered_at:'preflight'})}
  const resolution=gaps.some(g=>g.missing_tool)?'missing_tool':'missing_capability';return{resolution,selected_agent_ids:[],inactive_agent_ids:inactiveIds,uncovered_requirements:uncovered.map(r=>r.key),gaps,explanation:resolution==='missing_tool'?'Existing capability is blocked by tool availability.':'A required capability is genuinely uncovered.'}
 }
 private candidates():Candidate[]{const rows=this.db.prepare('SELECT id,enabled,paused FROM agents').all() as any[];const policies=this.db.prepare('SELECT agent_id,enabled,allowed_tools_json FROM agent_tool_policies').all() as any[];const pm=new Map(policies.map(p=>[p.agent_id,p])),ops=new AgentOperationsService(this.db);return rows.map(r=>{const p=pm.get(r.id);let tools:string[]=[];try{tools=p?.enabled?JSON.parse(p.allowed_tools_json||'[]'):[]}catch{}const eligible=ops.isEligible(r.id);return{id:r.id,enabled:Boolean(r.enabled)&&!Boolean(r.paused),healthy:eligible||(!r.enabled&&this.hasConfiguredRuntime(r.id)),caps:this.caps.listAgent(r.id),tools:new Set(tools)}})}
 private hasConfiguredRuntime(agentId:string){return Boolean(this.db.prepare(`SELECT 1 FROM agents a JOIN providers p ON p.id=a.provider_id AND p.enabled=1 JOIN provider_models m ON m.id=a.model_id AND m.enabled=1 WHERE a.id=?`).get(agentId))}
 private findExistingTeam(reqs:CapabilityRequirement[],tools:string[]){const teams=new TeamService(this.db);const eligible=teams.list().filter((t:any)=>t.enabled&&t.type==='permanent'&&t.owner_agent_id).map((t:any)=>{const c=teams.capabilities(t.id,reqs);const toolSet=new Set<string>((c.capabilities??[]).flatMap((x:any)=>x.tool_coverage??[]));return{id:t.id,member_count:(c.active_members??[]).length,ok:!(c.missing_capabilities??[]).length&&tools.every(x=>toolSet.has(x))}}).filter((x:any)=>x.ok&&x.member_count>0).sort((a:any,b:any)=>a.member_count-b.member_count||a.id.localeCompare(b.id));return eligible[0]??null}
 private quality(c:Candidate){return c.caps.reduce((s,x)=>s+score(x),0)}
 private minimumSet(active:Candidate[],reqs:CapabilityRequirement[],covers:(c:Candidate,r:CapabilityRequirement)=>boolean,toolOk:(c:Candidate)=>boolean){let remaining=[...reqs],pool=active.filter(toolOk),selected:Candidate[]=[];while(remaining.length){const ranked=pool.map(c=>({c,n:remaining.filter(r=>covers(c,r)).length,q:this.quality(c)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n||b.q-a.q||a.c.id.localeCompare(b.c.id));if(!ranked.length)break;const best=ranked[0].c;selected.push(best);pool=pool.filter(c=>c.id!==best.id);remaining=remaining.filter(r=>!covers(best,r))}
  for(let i=selected.length-1;i>=0;i--){const trial=selected.filter((_,j)=>j!==i);if(reqs.every(r=>trial.some(c=>covers(c,r))))selected=trial}return selected}
}
